export const ACTION_TYPE = {
  SET_USER: 'SET_USER',
  LOGOUT: 'LOGOUT',
  SET_POST_DATA: 'SET_POST_DATA',
  SET_POST_COMMENTS: 'SET_POST_COMMENTS',
  ADD_NEW_COMMENT: 'ADD_NEW_COMMENT',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
};
